version: 2.1

orbs:
  android: wordpress-mobile/android@0.0.22

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp gradle.properties-example gradle.properties

jobs:
  Lint:
    executor:
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Checkstyle & klint
          command: ./gradlew --stacktrace checkstyle ktlint
      - run:
          name: Lint
          command: ./gradlew --stacktrace lintVanillaRelease
      - android/save-gradle-cache
      - android/save-lint-results
  Test:
    executor:
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - android/restore-gradle-cache
      - copy-gradle-properties
      - run:
          name: Unit tests
          command: ./gradlew --stacktrace testVanillaRelease
      - android/save-gradle-cache
      - android/save-test-results

workflows:
  WooCommerce Android:
    jobs:
      - Lint
      - Test
